### PR TITLE
Pass document as the value of context to Drupal.attachBehaviors

### PR DESCRIPTION
**Pull request by philwolstenholme**
If we don't pass a value for context then things like `$('[data-video]', context)` in Drupal behaviors won't work, and code won't be shareable between Drupal and PL.

### CODE REVIEW

**Comment by evanmwillhite** [comment]
@philwolstenholme after the big changes just merged in https://github.com/fourkitchens/emulsify/pull/288 does this error still occur for you? Note: You'll have to use the develop branch to test since we haven't done a release yet. Thanks!

**Comment by evanmwillhite** [comment]
I went ahead and implemented this (in the new way) because the logic makes sense. I didn't see any functionality regressions within the default Pattern Lab components using javascript, so marking this as needs review since I tweaked the code.

**Comment by evanmwillhite** [comment]
Testing instructions on this one include testing the default Javascript components in Pattern Lab (accordion, menu, etc.)

**Review by mikeethedude — APPROVED** [review]
Looks good. No problems found.

**Pull request merged**
