### PR TITLE
Get rid of drush and use a plain PHP script for scaffolding

### PR DESCRIPTION
**Pull request by ccjjmartin**
Apparently I pushed this to the wrong repo.  Let me know if I should reopen this from Emulsify for consistency

## Addresses:
- https://github.com/fourkitchens/emulsify/issues/182

## Testing:
- Mess around with all the command line options:
```
    'arguments' => array(
      'human_readable_name' => 'The name of your theme.',
    ),
    'options' => array(
      'machine-name' => 'The machine-readable name of your theme. This will be auto-generated from the human_readable_name if ommited.',
      'description' => 'The description of your theme',
      'path' => 'Supports three options contrib, custom, none.  Defaults to "custom".',
      'slim' => 'Only copy base files',
    ),
```
- Example:
`php emulsify.php test2 --slim --machine-name awesome3 --path contrib --description "My really awesome description"`
`php emulsify.php -h` # for help

## Notes:
- I got tired of dependencies so the only dependency now is PHP

### CODE REVIEW

**Comment by thamas** [comment]
Great! Will check when I have time!

**Comment by thamas** [comment]
Just run `php emulsify.php "Emulsify Mutant" --machine-name emutant` and it created a copy of Emulsify at that moment when I hit Enter. Great! 👍

**Comment by thamas** [comment]
FYI `php emulsify.php -h` shows the same info in the "Examples" block as in the "Options" block.

**Comment by ccjjmartin** [comment]
@thamas Oops, copy paste fail.

**Comment by ddavidd** [comment]
I'm pretty excited about this. Just ran `php emulsify.php "Most Amazing" --machine-name amazing` and a copy was created as expected. 👍 Perhaps this goes without saying, but the [readme]( /fourkitchens/emulsify/blob/develop/README.md#in-a-composer-based-drupal-install-recommended) will need to be changed as well.

**Comment by backlineint** [comment]
I also ran into this issue with Drush 9 and found this as a workaround.  `php emulsify.php components-layout --machine-name components_layout --path custom --description "Components and Layouts Emulsify Subtheme"` worked nicely for me as well.

**Pull request merged**
