### PR TITLE
eliminating horizontal bar by switching to CSS Grid

### PR DESCRIPTION
**Pull request by shaal**
This is fixing #261 by switching to CSS Grid
+ fixing text input fields in the forms that are too wide on narrow screens

### CODE REVIEW

**Comment by ModulesUnraveled** [comment]
Hmm... This isn't really a Flexbox CSS grid thing. The wrapper mixin defines the bounds of a container element, and the breakout mixin allows an inner element to be edge to edge even when inside a "wrapped" element.

I tried your solution anyway, and got some unexpected space on the right side in Chrome and Safari (Firefox was fine) when I opted to "always show the scrollbar".

When I left it set to the default settings to hide the scrollbar when not in use, Safari had a weird bug where elements were vibrating on the screen. Basically jumping back and forth real fast any time I scrolled.

I think we need to keep working on this

**Comment by ModulesUnraveled** [comment]
I just read up on the technique you're using here and I like it. I have suggestions for the code, but it's 4am and I need too get back to sleep 😀 so I'll post it in the morning.

**Comment by ModulesUnraveled** [comment]
Okay, after trying to get this to work, I don't think it's possible to replace what we currently have with CSS grid.

**Main reason: Grandchildren can't breakout of the main content (e.g. be full width).**
[Take this example](https://codepen.io/tylersticka/pen/bWvaxP?editors=1100) and add a wrapper div around the `<div class="Prose-splash">` element, and you'll see it is no longer full width.

Since Drupal often gives us elements wrapped in a thousand divs, that makes this a deal breaker.

## Background
First, some background on why the overflow is happening:
Without scrollbars, the body elements value of 100% == 100vw.
With scrollbars, the body elements value of 100% == (100vw - [scrollbar-width])

_The width of scrollbars varies per browser, and per OS, so there's no easy way to calculate this without JS. I tried to get it via CSS calc, but wasn't able to do it. It may be possible, but I gave up._

Our current solution uses `calc(-50vw + 50%)` to get the value of the space on either side of the current element, and add that as a negative margin. Effectively pulling the element to the edges of the viewport.

```
// Given a viewport of 1500px
body {
  // Default width of 100%

  .wrapper {
    max-width: 1000px
  
    .element {
      // we want this to extend to 1500px
    }
  }
}
```
In this case, we can see that the wrapper is 1000px of the viewport's 1500px.
That means we need to add `margin-left: -250px` and `margin-right: -250px` in order to "break out" of the container, and make the element full browser width.

The above calculation would evaluate to this:
`calc(-750px + 500px)` Negative half of the viewport plus half of the element width equals `-250px`.

The Element's natural width of 1000px plus the extension of 250px each way makes the effective width == 1500px. The same as our viewport.

That's why this works.

## The Problem:
When scrollbars are shown, the body's 100% value is now `100vw - [scrollbar-width]`. On my machine the scroll bar is 15px, so body's 100% == 1485px.

Given the calculation above, our element's width is 1500px, but now our body is only 1480. That means we overflow the body by 15 pixels. The value of the scrollbar.

## Possible Solutions
We currently have two options that I see. I'm going to implement the second one now, and here's why:
### 1. `Overfow-x hidden`
```
body {
  overflow-x: hidden;
}
```
This would prevent the horizontal scrollbars that are a result of the extra 15px that the calculation produces.

**But it's an atomic bomb.**

The biggest issue being mobile. When content overflows the body (which can easily happen with large fonts, or images, or iframes, or [insert example here]) that content is inaccessible. We don't ever _want_ overflow issues to occur. But when they do, we want the content to at least be accessible, not irreversibly hidden.

You could of course, add `overflow: scroll` to virtually every element, but that's annoying, and a much worse option than #2 below.

### 2. Selectively add the wrapper mixin to elements
Instead of adding the wrapper to the `body`, or .`main` elements, and using breakout. Add the wrapper mixin to individual elements as you go.

This initially seemed really annoying to me, because I'd rather add the wrapper once, and then do extra work for breakouts, and switching to this means we have to do the "extra work" for every element I create.

After talking with @evanmwillhite though, he convinced me that it's the better solution, and the "extra work" is literally `@include wrapper`. So that's hardly a huge ask.

I'll create a PR to update this later today.

Comments are welcome

**Comment by shaal** [comment]
Since w3c already made a decision to avoid fixing the bug of 100vw+scrollbar
https://github.com/w3c/csswg-drafts/issues/1766#issuecomment-327642426
_RESOLVED: Drop the requirement to subtract scrollbar size from vh/vw units for overflow scroll_

In think that in order to avoid adding a javascript hack to solve the problem the clean solution would be using CSS Grid.

> Grandchildren can't breakout of the main content
Any grandchildren that need to breakout of the main content, should have their parent (the direct child of the grid container) breakout as well, by adding the same class of the main grid from before.

I created a codepen with the wrapper like you asked, and added a yellow border.
https://codepen.io/shaal-the-reactor/full/qKQxqr/

**Comment by ModulesUnraveled** [comment]
@shaal Unfortunately, your example still doesn't solve my issue because you're still adding grid-column: full;` to the immediate child of the grid.

That would be totally fine for PatternLab examples, but in Drupal you could have:
```
<body>
  <wrapper> // This has the site layout grid applied
    <section>
      <div>
        <div>
          <blockquote> // We want this to be full width
...
```

In that example, you'd have to make the `section` full width, and then do subgrids or something to make the things underneath it contained, and then full as needed.

That's not a method I would ever use.

**Comment by evanmwillhite** [comment]
As a slight aside, we also haven't moved Emulsify to CSS Grid support as we still have a fair number of clients to support on IE11 and there is no automated (e.g., autoprefixer) process to support that. The closest we've gotten so far is to include a [grid layout commented out](https://github.com/fourkitchens/emulsify/blob/develop/components/_patterns/00-base/layouts/_default.scss#L49-L73)  (vs the default flexbox) for when we can use CSS grid on a project.

**Comment by shaal** [comment]
@ModulesUnraveled I prepared a "Drupal" example, with super nested divs (and changed classes names so it will make more sense)
https://codepen.io/shaal-the-reactor/full/pKQVNK/

The direct child of the grid has to have "breakout", after that - you are free to work with the full width. and add "mygrid" any time you want the same grid structure.

anyway, it's definitely not nice anymore :) :) :)

**Comment by ModulesUnraveled** [comment]
I'm going to close this for now, since https://github.com/fourkitchens/emulsify/pull/269 will fix the original issue.

If you want to create a followup PR where this is commented out by default, feel free to do that

**Comment by ModulesUnraveled** [comment]
I'm sorry, I don't understand your second paragraph.

But to respond to the "always subtract a default scrollbar width":
That's not easy since browsers have different scrollbar widths, and things like phones/tablets/etc don't usually have one at all

**Comment by ByteEater-pl** [comment]
You're referring to my deleted comment. I had this issue open in a tab and accidentally commented here. When I realized this, I copied and pasted there: https://github.com/w3c/csswg-drafts/issues/1766#issuecomment-460321819.

**Comment by ModulesUnraveled** [comment]
Gotcha! 👍

**Pull request closed without merging**
