### PR TITLE
EM-9: BUGFIX: Fix bem function to not pass added classes to children

### PR DESCRIPTION
**Pull request by JeffTomlinson**

### CODE REVIEW

**Comment by amazingrando** [comment]
Tested this with a fresh D8 site and the BEM function worked well. I'm going to let @evanmwillhite or @ModulesUnraveled give the final review for approval.

**Comment by evanmwillhite** [comment]
The behavior is still there - sorry we didn't include a better description of it (classes are inherited from parent to child when the parent template is using an include). 

That said, I've pushed up an approach, and I'm not sure if it is going to work or not because it is a pretty fundamental change to how we would write our include/embed statements (but supported in Twig). I added in a change to the `components/_patterns/03-organisms/_node.twig` template (to use the heading template via an include in the teaser, which is what it should do anyway). The key is in the include statement I've used the `only` keyword. We namespace everything in our templates so as to avoid inheritance issues, so this just extends that behavior to variables like attributes being passed through. Not sure if it's the right approach, and we would need to tweak a lot of Emulsify templates to suit, but... 

**To test:**
- [ ] Add article content to your site and promote to front.
- [ ] Visit your homepage logged-in and inspect the elements to make sure the contextual-region class isn't being passed down to the .h2 or .h2__link elements

screen shot 2017-07-24 at 10 14 40 pm

**Comment by JeffTomlinson** [comment]
@evanmwillhite let's discuss in the morning. I think I misunderstood the scope of the issue. I thought we were just trying to fix the class attribute. The problem as I see it is we are outputting _all_ element attributes via a function named `bem` which seems semantically weird to me. To my thinking a function named `bem` should only be outputting classes. I thing we should hand non-class attributes separately. Anyway, I have another potential solution that does this and doesn't seem to rely on the `only` keyword but let's review together before I commit.

**Comment by evanmwillhite** [comment]
I hear you on the name of bem being weird in that it hands back all the attributes. I was thinking more of the fact that it only seeks to _interact_ with the classes so the name makes sense from that side but from a debugging standpoint you're right - you don't exactly expect it to hand back all the classes. We could keep the two separate, but I was trying to avoid this long-winded approach:

`<div{{ bem(classes) }}{{ attributes|without('class') }}>`

I'd definitely be open to another solution besides mine though. I'm not really happy with using the only variable - I'd rather somehow do a similar thing but within the BEM function.

**Comment by evanmwillhite** [comment]
Duplicate and fixed in https://github.com/fourkitchens/emulsify/pull/114

**Pull request closed without merging**
