### PR TITLE
Changes for adding babel, removing global JS

### PR DESCRIPTION
**Pull request by evanmwillhite**
## Add ES6 support (Babel)
_Companion PR for Emulsify Gulp's https://github.com/fourkitchens/emulsify-gulp/pull/64_

**Features:**
- Support ES6 syntax
- Uses Babel to compile JS to dist directory using component file path (`dist/02-molecules/accordion-item/accordion-item.js`
- Uses Sourcemaps for debugging original code in browser
- Removes global.js file and libraries.yml reference (not used often and too easy to misuse)

**To test:**
- [x] Clone a fresh copy of Emulsify
- [x] `composer install`
- [x] Change line 6 in package.json to `"emulsify-gulp": "fourkitchens/emulsify-gulp#add-babel",`
- [x] `yarn install`
- [x] `yarn start`
- [x] Verify start command runs without errors
- [x] Verify dist files and sourcemaps are created correctly
- [x] Verify [Pattern Lab components with JavaScript work OK](http://localhost:3000/pattern-lab/public/?p=viewall-molecules-accordion-item)

**Post-merge**
1. In Emulsify Gulp, merge in https://github.com/fourkitchens/emulsify-gulp/pull/64 and merge develop into master and deploy master (also in Emulsify Gulp).
2. Edit [any instructions for Javascript in Drupal](https://github.com/fourkitchens/emulsify/wiki/Drupal-Usage#javascript-in-drupal) to remove references to global.js

### CODE REVIEW

**Comment by ModulesUnraveled** [comment]
@evanmwillhite I'm getting this error on `yarn start`

```
yarn start                                                                           11:39:10
yarn start v0.21.3
$ gulp clean && gulp compile && gulp theme
module.js:472
    throw err;
    ^

Error: Cannot find module 'gulp-uglify'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (/Websites/GitProjects/emulsify-pr-review/node_modules/emulsify-gulp/index.js:16:18)
    at /Websites/GitProjects/emulsify-pr-review/gulpfile.js:16:27
    at Object.<anonymous> (/Websites/GitProjects/emulsify-pr-review/gulpfile.js:18:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
error Command failed with exit code 1.
```

**Comment by ModulesUnraveled** [comment]
I'm also curious about the repercussions of releasing a new emulsify-gulp. Is that being versioned now? Or will the update break backward compatibility for anyone?

**Comment by ModulesUnraveled** [comment]
I think I know why I'm getting the uglify error. Seeing if I can fix that now. (TL;DR: Used an existing install, so the yarn.lock was already created)

**Comment by ModulesUnraveled** [comment]
W00t! Works great!

**Comment by ModulesUnraveled** [comment]
:shipit:

image

**Comment by infiniteluke** [comment]
One test step that was missed here was to ensure the source maps work. Luckily they do!

screen_shot_2017-10-18_at_11_11_00_am

**Pull request merged**
