### PR TITLE
Refactor Lists

### PR DESCRIPTION
**Pull request by ccjjmartin**
## Purpose:
- Refactor Lists

## Description:
- Lists were originally atoms, this PR updates them to be organisms and adds a lot of flexibility.
- It extends definition lists to be able to use multiple terms and definitions
- I also used the changes to the definition lists to update the accordion
- There was a weird bug on the accordion that only showed the accordion definition on the page (so when multiple accordions were on a page the bug appeared)
- Documentation was double checked
- Checked that top components allow for bottom components variables
- Refactored the accordion item to be part of the definition item molecule

## Possible future PRs:
- Add attribute support across the project for multi-lingual purposes and other purposes
- Look at refactoring the way we display classes

### CODE REVIEW

**Comment by evanmwillhite** [comment]
@ccjjmartin I've looked at this and it is definitely more flexible. Can we chat through this in our next Frontend practice group?

**Comment by ccjjmartin** [comment]
@evanmwillhite Definitely!  Also I merged the t function PR into master but this one is based on develop should I switch the base branch on this to `master`?

**Comment by evanmwillhite** [comment]
Yea, for now @ccjjmartin. We'll switch workflow soon.

**Comment by ccjjmartin** [comment]
Brian's work will overwrite this, closing.

**Pull request closed without merging**
